export const SEARCH_SECTIONS_SORT_ORDER = [
    'Collections',
    'Playlists',
    'Movies',
    'Shows',
    'Episodes',
    'People',
    'Studios',
    'Artists',
    'Albums',
    'Songs',
    'HeaderVideos',
    'Programs',
    'Channels',
    'HeaderPhotoAlbums',
    'Photos',
    'HeaderAudioBooks',
    'Books'
];
